### ISSUE TITLE
Navigation bar not visible

### ISSUE THREAD

**Issue by Jashan2055** [JaiveerSingh2004/SCM_PR-05#1]
The navigation bar of the page is not visible.
![WhatsApp Image 2024-05-05 at 12 50 01_22a22fdb](https://github.com/JaiveerSingh2004/SCM_PR-05/assets/156660977/4f6f0f4f-38dd-40aa-a173-b5aea53f7a52)

**Comment by JaiAditya21** [comment]
Fixed Navbar issue and Improved Functionality of the Navigation bar
![Screenshot 2024-05-05 125616](https://github.com/JaiveerSingh2004/SCM_PR-05/assets/156660457/30c0688a-a25b-4c8c-a081-cac7f712c1f1)
